# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-23 07:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixed_period', models.CharField(blank=True, max_length=100, null=True)),
                ('timedelta_period', models.DurationField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('last_update_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('start_time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('editors', models.ManyToManyField(related_name='can_edit', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker_app.TaskModel')),
            ],
        ),
        migrations.AddField(
            model_name='planmodel',
            name='created_tasks',
            field=models.ManyToManyField(blank=True, related_name='children', to='tracker_app.TaskModel'),
        ),
        migrations.AddField(
            model_name='planmodel',
            name='task_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker_app.TaskModel'),
        ),
    ]
